In [2]:
# importar a biblioteca
import numpy as np

In [6]:
# Criar um array
array = np.array([1, 3, 5, 7])
print(array)

[1 3 5 7]


In [9]:
#Tipo: type()
print(type(array))

<class 'numpy.ndarray'>


In [10]:
# Definir o tipo dos elementos
# Array de floats
array_float = np.array([1.2, 3.6, 4.99999])
print(array_float)

[1.2     3.6     4.99999]


In [13]:
array_float = np.array([1, 2, 30], dtype = np.float64)
print(array_float)

[ 1.  2. 30.]


In [14]:
# Array de inteiros
array_int = np.array([1, 2, 30], dtype = np.int32)
print(array_int)

[ 1  2 30]


In [19]:
#Alterar o tipo do array

In [20]:
# Alterar de float para inteiro
array1 = np.array([1.2, 4.8, 8.3, 9.999])

array1_convertido = array1.astype(np.int32)
print(array1_convertido)

[1 4 8 9]


In [21]:
# Alterar de inteiro para float
array2 = np.array([1, 6, 8, 3])

array2_int = array2.astype(np.float64)
print(array2_int)

[1. 6. 8. 3.]


In [23]:
## Arrays multidimensionais


In [24]:
# Criar um array bidimensional (matriz)
# linhas X colunas 
matriz = np.array([[1, 2, 3], [3, 4, 5]])
print(matriz)

[[1 2 3]
 [3 4 5]]


In [25]:
# Para verificar o formato (tamanho) da matriz 
print(matriz.shape)

(2, 3)


In [26]:
# Criar uma matriz contendo elementos de valor zero
matriz_zero = np.zeros([4, 2])
print(matriz_zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [27]:
#Criar uma matriz contendo 1
matriz_um = np.ones([3, 4])
print(matriz_um)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
# Criar uma matriz 2 X 3 de 0 inteiros 
matriz_zero_int = np.zeros([2, 3], dtype = np.int32)
print(matriz_zero_int)


[[0 0 0]
 [0 0 0]]


In [29]:
#Matriz identidade
# Matriz quadrada (mesmo número de linhas e colunas)
# Diagonal principal tem valor 1
matriz_identidade = np.eye(3)
print(matriz_identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
### Valores aleatórios

In [31]:
# Array com valores aleatórios entre 0 e 1
array_aleatorio = np.random.random(4)
print(array_aleatorio)

[0.47328058 0.19559475 0.20184535 0.93738945]


In [32]:
# Matriz com valores aleatórios entre 0 e 1
matriz_aleatoria = np.random.random([2, 3])
print(matriz_aleatoria)


[[0.66849085 0.69627038 0.11820238]
 [0.07619708 0.81379438 0.25788256]]


In [33]:
# Array de valores aleatorios inteiros
array_ale_int = np.random.randint(4, size = 5) #0, 1, 2, 3
print(array_ale_int)

[1 3 0 2 2]


In [34]:
# Matriz de valores aleatorios inteiros
matriz_ale_int = np.random.randint(11, size = (3, 4))
print(matriz_ale_int)

[[5 9 0 9]
 [3 1 0 8]
 [4 3 0 4]]


In [35]:
## Funções Matemáticas


In [36]:
# Criar uma matriz para testes
matriz_teste = np.array([[1, 4, 5], [12, -3, 8]])
print(matriz_teste)

[[ 1  4  5]
 [12 -3  8]]


In [37]:
# Maior valor da matriz
print(matriz_teste.max())

12


In [38]:
# Menor valor da matriz
print(matriz_teste.min())


-3


In [39]:
# Soma dos valores da matriz
print(matriz_teste.sum())

27


In [40]:
# Média dos valores da matriz
print(matriz_teste.mean())

4.5


In [41]:
 # Raiz quadrada
matriz_teste2 = np.array([[4, 9, 25], [16, 64, 36], [81, 49, 100]])
print(matriz_teste2)                   

[[  4   9  25]
 [ 16  64  36]
 [ 81  49 100]]


In [42]:
print(np.sqrt(matriz_teste2))


[[ 2.  3.  5.]
 [ 4.  8.  6.]
 [ 9.  7. 10.]]


In [43]:
# Potências
array_teste = np.array([2, 3, 5])

#Quadrado dos elementos
print(np.power(array_teste, 2))

[ 4  9 25]


In [44]:
# Elementos elevados à 3a. potência
print(np.power(array_teste, 3))


[  8  27 125]


In [45]:
####Extração de elementos

In [52]:
array_teste = np.array([1, 3, 5, 7, 8, 6, 4])
print(array_teste)

[1 3 5 7 8 6 4]


In [50]:
# Primeiro elemento do array
print(array_teste[0])

1


In [48]:
# Terceiro elemento do array
print(array_teste[2])

5


In [49]:
# Intervalo entre o 3o e 5o elementos
print(array_teste[2:5])

[5 7 8]


In [ ]:
# Três primeiros elementos do array
print(array_teste[:3])

In [53]:

# Exibir os 4 últimos elementos do array
print(array_teste[-4:])

[7 8 6 4]


In [54]:
# Exibir os elementos a partir da posição 2 até o final
print(array_teste[2:])

[5 7 8 6 4]


In [55]:
## Extração dos elementos da matriz

In [56]:
# Criar uma matriz teste
matriz_teste = np.array([[4, 2, 1], [5, 3, 7], [6, 8, 9]])
print(matriz_teste)

[[4 2 1]
 [5 3 7]
 [6 8 9]]


In [57]:
#Exibindo o elemento 2o. elemento da primeira linha
print(matriz_teste[0, 1])

2


In [58]:
#Exibir a segunda linha
print(matriz_teste[1, :])
print(matriz_teste[1])

[5 3 7]
[5 3 7]


In [59]:
#Exibir a terceira coluna
print(matriz_teste[:, 2])

[1 7 9]


In [60]:
'''
Imprimir a matriz 
[2 1]
[3 7]
'''
print(matriz_teste[:2, 1:])


[[2 1]
 [3 7]]


In [61]:
###Operações entre matrizes

In [62]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print(m1)
print("-----------")
print(m2)

[[1 2]
 [3 4]]
-----------
[[5 6]
 [7 8]]


In [65]:
# Soma
# O tamanho das matrizes deve ser igual
print(m1 + m2)

[[ 6  8]
 [10 12]]


In [64]:
#Subtração
print(m1 - m2)


[[-4 -4]
 [-4 -4]]


In [ ]:
# Caso especial
m3 = np.array([0, 1])

print(m1 + m3)

In [66]:
# Multiplicação entre matrizes
print(m1 * m2)

[[ 5 12]
 [21 32]]


In [67]:
# Multiplicação entre matrizes da forma matemática
print(np.dot(m1, m2))

[[19 22]
 [43 50]]


In [69]:
###Where


In [70]:
#Criar uma matriz 3 x3
matriz3 = np.array([[0, 1, 3], [-2, 5, 8], [4, -12, 7]])
print(matriz3)

[[  0   1   3]
 [ -2   5   8]
 [  4 -12   7]]


In [71]:
# Criar uma nova matriz contendo valores 0, onde o elemento é menor que 4
# e 1, nos outros casos
# Semelhante ao operador ternário
matriz_nova = np.where(matriz3 < 4, 0, 1)
print(matriz_nova)

[[0 0 0]
 [0 1 1]
 [1 0 1]]
